name: Aseprite Linux x64 Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install base tools
        run: sudo apt-get update && sudo apt-get install -y git curl unzip jq

      - name: Get latest stable release
        run: |
          releases=$(curl -s https://api.github.com/repos/aseprite/aseprite/releases)

          tag=$(echo "$releases" | jq -r '
            map(select(.draft==false and .prerelease==false))
            | sort_by(.published_at)
            | reverse
            | .[0].tag_name
          ')

          echo "ASEPRITE_TAG=$tag" >> $GITHUB_ENV

      - name: Clone Aseprite
        run: |
          git clone --recursive https://github.com/aseprite/aseprite.git aseprite
          cd aseprite
          git checkout $ASEPRITE_TAG

      - name: Resolve Skia URL
        run: |
          cd aseprite/laf/misc
          chmod +x skia-url.sh
          url=$(./skia-url.sh release linux x64)
          echo "SKIA_URL=$url" >> $GITHUB_ENV

      - name: Download Skia
        run: curl -L "$SKIA_URL" -o skia.zip

      - name: Validate Skia
        run: test -s skia.zip || exit 1

      - name: Extract Skia
        run: |
          Remove-Item -Recurse -Force "$env:DEPS_DIR\skia"
          mkdir -p deps/skia
          unzip skia.zip -d deps/skia

      - name: Install build tools
        run: sudo apt-get install -y cmake ninja-build clang

      - name: Configure
        run: |
          cmake -G Ninja \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=deps/skia \
            -S aseprite \
            -B build

      - name: Build
        run: cmake --build build --target aseprite

      - name: Package
        run: |
          mkdir dist
          cp build/bin/aseprite dist/
          zip -r aseprite-linux.zip dist

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.ASEPRITE_TAG }}
          files: aseprite-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
