name: macOS x64 Aseprite

on:
  workflow_call:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Setup
        run: |
          export ASEPRITE_DIR=$GITHUB_WORKSPACE/aseprite
          export DEPS_DIR=$GITHUB_WORKSPACE/deps
          export BUILD_DIR=$GITHUB_WORKSPACE/build

          mkdir -p $ASEPRITE_DIR $DEPS_DIR $BUILD_DIR

      - name: Install tools
        run: brew install cmake ninja git curl unzip

      - name: Clone
        run: |
          git clone --recursive https://github.com/aseprite/aseprite.git aseprite
          test -f aseprite/CMakeLists.txt || exit 1

      - name: Skia
        run: |
          curl -L "https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-macOS-Release-x64.zip" -o skia.zip
          mkdir -p deps/skia
          unzip -o skia.zip -d deps/skia

      - name: Debug
        run: |
          ls aseprite
          ls deps/skia

      - name: Configure
        run: |
          cmake -G Ninja \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=$GITHUB_WORKSPACE/deps/skia \
            -S $GITHUB_WORKSPACE/aseprite \
            -B $GITHUB_WORKSPACE/build

      - name: Build
        run: cmake --build build --target aseprite -v
